# Generated by Django 4.2.5 on 2023-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.CharField(max_length=600)),
                ('data2', models.CharField(max_length=600)),
                ('data3', models.CharField(max_length=600)),
                ('data4', models.CharField(max_length=600)),
                ('data5', models.CharField(max_length=600)),
            ],
        ),
    ]
